# only used for debug and developmetn only
services:
  ollama:
    build:
      context: ./dockerfile/ollama
    ports:
      - "11434:11434"
    volumes:
      - .data/ollama:/root/.ollama

  db:
    image: pgvector/pgvector:pg16 # Uses Postgres 16 with pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vizier
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - .data/postgresql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_gui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
